# Generated by scripts/packaging.js in PierreEbele/cadenas. Do not edit by hand.
class Cadenas < Formula
  desc "Encrypt a file with a password; age-compatible"
  homepage "https://github.com/PierreEbele/cadenas"
  url "https://registry.npmjs.org/cadenas/-/cadenas-1.7.0.tgz"
  sha256 "595a2f942c26a605b841eb1710d414a4c71e2e68705681029d25bf2a44ed1bcd"
  license "MIT"

  depends_on "node"

  def install
    system "npm", "install", *std_npm_args
    bin.install_symlink libexec.glob("bin/*")
  end

  test do
    assert_equal version.to_s, shell_output("#{bin}/cadenas --version").strip
    (testpath/"password").write "correct horse battery staple\n"
    (testpath/"note.txt").write "hello"
    system bin/"cadenas", "lock", "--password-file", "password", "note.txt"
    system bin/"cadenas", "unlock", "--password-file", "password", "-o", "out.txt", "note.txt.cadenas"
    assert_equal "hello", (testpath/"out.txt").read
  end
end
